apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: {{ .Values.backend.pv.bindSourceCode.pvcName }}
  # annotations:
  #   "helm.sh/resource-policy": keep
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 1Gi
  storageClassName: manual
  volumeName: {{ .Values.backend.pv.bindSourceCode.pvName }}
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: {{ .Values.backend.pv.bindData.pvcName }}
  # annotations:
  #   "helm.sh/resource-policy": keep
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 1Gi
  storageClassName: manual
  volumeName: {{ .Values.backend.pv.bindData.pvName }}
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: {{ .Values.database.pv.bindData.pvcName }}
  # annotations:
  #   "helm.sh/resource-policy": keep
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 1Gi
  storageClassName: manual
  volumeName: {{ .Values.database.pv.bindData.pvName }}