const FileSystemActionTypes = {
  //File System Reset
  FILE_SYSTEM_RESET: "FILE_SYSTEM_RESET",

  //#region //* ------ Global State ------ *//
  SET_SELECTED_FOLDER: "SET_SELECTED_FOLDER",
  SET_IS_LABEL_MODE: "SET_IS_LABEL_MODE",
  SET_IS_DELETE_MODE: "SET_IS_DELETE_MODE",
  SET_IS_EXPORT_MODE: "SET_IS_EXPORT_MODE",
  SET_SELECTED_IMAGES: "SET_SELECTED_IMAGES",
  SET_IMAGES_IN_LABEL: "SET_IMAGES_IN_LABEL",
  SET_CLASS_IMAGES_IN_LABEL: "SET_CLASS_IMAGES_IN_LABEL",
  SET_CHECKBOX_STATUS: "SET_CHECKBOX_STATUS",
  SET_IS_FILE_UPLOADING: "SET_IS_FILE_UPLOADING",
  //#endregion

  //#region //* ------ Get total file memories ------ *//
  GET_FILE_MEMORY_START: "GET_FILE_MEMORY_START",
  GET_FILE_MEMORY_SUCCESS: "GET_FILE_MEMORY_SUCCESS",
  GET_FILE_MEMORY_FAILURE: "GET_FILE_MEMORY_FAILURE",
  //#endregion

  //#region //* ------ Get Folder Hierarchy ------ *//
  GET_FOLDER_HIERARCHY_START: "GET_FOLDER_HIERARCHY_START",
  GET_FOLDER_HIERARCHY_SUCCESS: "GET_FOLDER_HIERARCHY_SUCCESS",
  GET_FOLDER_HIERARCHY_FAILURE: "GET_FOLDER_HIERARCHY_FAILURE",
  //#endregion

  //#region //* ------ Create Folder Hierarchy ------ *//
  CREATE_FOLDER_HIERARCHY_START: "CREATE_FOLDER_HIERARCHY_START",
  CREATE_FOLDER_HIERARCHY_SUCCESS: "CREATE_FOLDER_HIERARCHY_SUCCESS",
  CREATE_FOLDER_HIERARCHY_FAILURE: "CREATE_FOLDER_HIERARCHY_FAILURE",
  //#endregion

  //#region //* ------ Homepage ID ------ *//
  GET_HOMEPAGE_ID_START: "GET_HOMEPAGE_ID_START",
  GET_HOMEPAGE_ID_SUCCESS: "GET_HOMEPAGE_ID_SUCCESS",
  GET_HOMEPAGE_ID_FAILURE: "GET_HOMEPAGE_ID_FAILURE",
  //#endregion

  //#region //* ------ Current Page ID ------ *//
  GET_CURRENT_PAGE_START: "GET_CURRENT_PAGE_START",
  GET_CURRENT_PAGE_SUCCESS: "GET_CURRENT_PAGE_SUCCESS",
  GET_CURRENT_PAGE_FAILURE: "GET_CURRENT_PAGE_FAILURE",
  //#endregion

  //#region //* ------ Current Page Files ------ *//
  GET_FILES_START: "GET_FILES_START",
  GET_FILES_SUCCESS: "GET_FILES_SUCCESS",
  GET_FILES_FAILURE: "GET_FILES_FAILURE",
  //#endregion

  //#region //* ------ Load Files v1 ------ *//
  LOAD_FILES_V1_START: "LOAD_FILES_V1_START",
  LOAD_FILES_V1_SUCCESS: "LOAD_FILES_V1_SUCCESS",
  LOAD_FILES_V1_FAILURE: "LOAD_FILES_V1_FAILURE",
  //#endregion

  //#region //* ------ Check is file labelled ------ *//
  CHECK_IS_FILE_LABELLED_START: "CHECK_IS_FILE_LABELLED_START",
  CHECK_IS_FILE_LABELLED_SUCCESS: "CHECK_IS_FILE_LABELLED_SUCCESS",
  CHECK_IS_FILE_LABELLED_FAILURE: "CHECK_IS_FILE_LABELLED_FAILURE",

  //#endregion

  //#region //* ------ Create Folder ------ *//
  CREATE_FOLDER_START: "CREATE_FOLDER_START",
  CREATE_FOLDER_SUCCESS: "CREATE_FOLDER_SUCCESS",
  CREATE_FOLDER_FAILURE: "CREATE_FOLDER_FAILURE",
  //#endregion

  //#region //* ------ Upload Files ------ *//
  UPLOAD_FILES_START: "UPLOAD_FILES_START",
  UPLOAD_FILES_SUCCESS: "UPLOAD_FILES_SUCCESS",
  UPLOAD_FILES_FAILURE: "UPLOAD_FILES_FAILURE",
  //#endregion

  //#region //* ------ Download Files & Folders ------ *//
  DOWNLOAD_FILES_START: "DOWNLOAD_FILES_START",
  DOWNLOAD_FILES_SUCCESS: "DOWNLOAD_FILES_SUCCESS",
  DOWNLOAD_FILES_FAILURE: "DOWNLOAD_FILES_FAILURE",

  DOWNLOAD_FOLDERS_START: "DOWNLOAD_FOLDERS_START",
  DOWNLOAD_FOLDERS_SUCCESS: "DOWNLOAD_FOLDERS_SUCCESS",
  DOWNLOAD_FOLDERS_FAILURE: "DOWNLOAD_FOLDERS_FAILURE",
  //#endregion

  //#region //* ------ Delete Files & Folders ------ *//
  DELETE_FILES_START: "DELETE_FILES_START",
  DELETE_FILES_SUCCESS: "DELETE_FILES_SUCCESS",
  DELETE_FILES_FAILURE: "DELETE_FILES_FAILURE",

  DELETE_FOLDERS_START: "DELETE_FOLDERS_START",
  DELETE_FOLDERS_SUCCESS: "DELETE_FOLDERS_SUCCESS",
  DELETE_FOLDERS_FAILURE: "DELETE_FOLDERS_FAILURE",
  //#endregion
};

export default FileSystemActionTypes;
