variables:
  SMA_TOKEN_PASSWORD: "_seJFZUMQxiwL9AzTFDo"

BuildDocker:
  image: docker:latest
  stage: build
  services:
    - docker:dind
  before_script:
    - docker info
    #  - echo $CI_BUILD_TOKEN | docker login -u "$CI_REGISTRY_USER" --password-stdin $CI_REGISTRY
    - docker login registry.gitlab.com -u smaci -p $SMA_TOKEN_PASSWORD
  script:
    - echo "${CI_REGISTRY_IMAGE}:latest"
    - docker build --pull -t "${CI_REGISTRY_IMAGE}:latest" . --no-cache
    - docker push "${CI_REGISTRY_IMAGE}:latest"
  only:
    refs:
      - master
      - merge_requests

DeployDocker:
  image: docker:latest
  stage: deploy
  services:
    - docker:dind
  before_script:
    - docker login registry.gitlab.com -u smaci -p $SMA_TOKEN_PASSWORD
    # - echo $CI_BUILD_TOKEN | docker login -u "$CI_REGISTRY_USER" --password-stdin $CI_REGISTRY
  script:
    - echo "${CI_REGISTRY_IMAGE}:${CI_COMMIT_TAG}"
    - docker build --pull -t "${CI_REGISTRY_IMAGE}:${CI_COMMIT_TAG}" . --no-cache
    - docker push "${CI_REGISTRY_IMAGE}:${CI_COMMIT_TAG}"
  only:
    refs:
      - tags
